name: Update headlines

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          pip install -r requirements.txt
          python build.py
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html page2.html berita.txt headlines/*.json
          git commit -m "Auto update $(date -u +'%Y-%m-%d %H:%M')" || echo "No changes"
          git push
